print ('======DESAFIO 1 ! ======')
nome = input ('ola usuario, como gostaria de ser chamado? ')
print('seja muito bem vindo ao desafio 1 Sr(a)', nome)
print('vamos estar fazendo algumas perguntas por favor colabore')
ano = input('qual ano você nasceu? (modelo de resposta -1997-) ')
mes = input ('qual o mes do seu nascimento? (modelo de resposta - março- ')
dia = input ('qual dia do seu nascimento? (modelo de resposta -31- ') 
print(nome,'você nasceu no dia ', dia,'do mês de ', mes,'do ano ',ano, 'correto?' )
